"""Print queue operations shared by the REST viewset and the MCP toolset."""

from __future__ import annotations

from nextintranet_backend.models.printList import PrintList


def sync_default_print_list(instance: PrintList, requested_default: bool | None = None) -> PrintList:
    """Keep at most one default queue per owner, and make sure the owner has one.

    Passing requested_default=True promotes the queue and demotes its siblings.
    """
    if requested_default is True:
        PrintList.objects.filter(owner=instance.owner).exclude(id=instance.id).update(is_default=False)
        if not instance.is_default:
            instance.is_default = True
            instance.save(update_fields=["is_default"])
        return instance

    if not PrintList.objects.filter(owner=instance.owner, is_default=True).exists():
        instance.is_default = True
        instance.save(update_fields=["is_default"])

    return instance


def create_print_list(owner, *, name: str = "", is_public: bool = True, is_default: bool | None = None) -> PrintList:
    """Create a print queue for owner. An empty name is auto-generated by PrintList.save()."""
    queue = PrintList.objects.create(
        owner=owner,
        name=name or "",
        is_public=is_public,
        is_default=False,
    )
    return sync_default_print_list(queue, is_default)
