# Generated by Django 5.1.2 on 2025-10-24 10:19

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nextintranet_warehouse', '0031_alter_stockoperation_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Název složky', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Popis složky', null=True, verbose_name='Description')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Nadřazená složka', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nextintranet_production.productionfolder', verbose_name='Parent folder')),
            ],
            options={
                'verbose_name': 'Production Folder',
                'verbose_name_plural': 'Production Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Název výrobního projektu', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Popis výrobního projektu', null=True, verbose_name='Description')),
                ('folder', models.ForeignKey(help_text='Složka, ve které je production uložena', on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='nextintranet_production.productionfolder', verbose_name='Folder')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Název šablony', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Popis šablony', null=True, verbose_name='Description')),
                ('version', models.CharField(blank=True, help_text='Verze šablony (např. v1.0, v2.1)', max_length=50, null=True, verbose_name='Version')),
                ('production', models.ForeignKey(help_text='Výrobní projekt, ke kterému šablona patří', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='nextintranet_production.production', verbose_name='Production')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['production', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Název realizace', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Popis realizace', null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Stav realizace', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, help_text='Čas zahájení výroby', null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Čas dokončení výroby', null=True, verbose_name='Completed at')),
                ('production', models.ForeignKey(help_text='Výrobní projekt, ke kterému realizace patří', on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='nextintranet_production.production', verbose_name='Production')),
                ('template', models.ForeignKey(help_text='Šablona, ze které realizace vychází', on_delete=django.db.models.deletion.PROTECT, related_name='realizations', to='nextintranet_production.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Realization',
                'verbose_name_plural': 'Realizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(help_text='Množství součástky potřebné v šabloně', verbose_name='Quantity')),
                ('position', models.PositiveIntegerField(default=0, help_text='Pozice v seznamu (pro řazení)', verbose_name='Position')),
                ('notes', models.TextField(blank=True, help_text='Poznámky k součástce v šabloně', null=True, verbose_name='Notes')),
                ('component', models.ForeignKey(help_text='Součástka ze skladu', on_delete=django.db.models.deletion.PROTECT, related_name='template_usages', to='nextintranet_warehouse.component', verbose_name='Component')),
                ('template', models.ForeignKey(help_text='Šablona, ke které součástka patří', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='nextintranet_production.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Component',
                'verbose_name_plural': 'Template Components',
                'ordering': ['template', 'position', 'component__name'],
                'unique_together': {('template', 'component')},
            },
        ),
        migrations.CreateModel(
            name='RealizationComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(help_text='Množství součástky použité v realizaci', verbose_name='Quantity')),
                ('position', models.PositiveIntegerField(default=0, help_text='Pozice v seznamu (pro řazení)', verbose_name='Position')),
                ('notes', models.TextField(blank=True, help_text='Poznámky k součástce v realizaci', null=True, verbose_name='Notes')),
                ('is_modified', models.BooleanField(default=False, help_text='Označuje, zda byla součástka upravena oproti šabloně', verbose_name='Is modified')),
                ('component', models.ForeignKey(help_text='Součástka ze skladu', on_delete=django.db.models.deletion.PROTECT, related_name='realization_usages', to='nextintranet_warehouse.component', verbose_name='Component')),
                ('realization', models.ForeignKey(help_text='Realizace, ke které součástka patří', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='nextintranet_production.realization', verbose_name='Realization')),
                ('template_component', models.ForeignKey(blank=True, help_text='Původní součástka ze šablony (pokud existuje)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realization_components', to='nextintranet_production.templatecomponent', verbose_name='Template Component')),
            ],
            options={
                'verbose_name': 'Realization Component',
                'verbose_name_plural': 'Realization Components',
                'ordering': ['realization', 'position', 'component__name'],
            },
        ),
    ]
