# Generated by Django 5.1.2 on 2025-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatecomponent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='realizationcomponent',
            name='quantity',
        ),
        migrations.AddField(
            model_name='realizationcomponent',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Další atributy součástky (JSON)', null=True, verbose_name='Attributes'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Další atributy součástky (JSON)', null=True, verbose_name='Attributes'),
        ),
        migrations.RemoveField(
            model_name='templatecomponent',
            name='quantity',
        ),
    ]
