# Generated by Django 5.1.2 on 2025-10-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0002_alter_templatecomponent_unique_together_and_more'),
        ('nextintranet_warehouse', '0031_alter_stockoperation_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='component_reference',
            field=models.ForeignKey(blank=True, help_text='Odkaz na skladovou položku (pokud production odpovídá konkrétní součástce)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='nextintranet_warehouse.component', verbose_name='Component Reference'),
        ),
        migrations.AddField(
            model_name='production',
            name='link',
            field=models.URLField(blank=True, help_text='HTTP odkaz související s výrobním projektem (např. dokumentace, specifikace)', null=True, verbose_name='Link'),
        ),
    ]
