# Generated by Django 5.1.2 on 2025-10-24 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0003_production_component_reference_production_link'),
        ('nextintranet_warehouse', '0031_alter_stockoperation_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realizationcomponent',
            options={'ordering': ['realization', 'position'], 'verbose_name': 'Realization Component', 'verbose_name_plural': 'Realization Components'},
        ),
        migrations.AlterModelOptions(
            name='templatecomponent',
            options={'ordering': ['template', 'position'], 'verbose_name': 'Template Component', 'verbose_name_plural': 'Template Components'},
        ),
        migrations.AlterField(
            model_name='realizationcomponent',
            name='component',
            field=models.ForeignKey(blank=True, help_text='Součástka ze skladu (pokud byla nalezena)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realization_usages', to='nextintranet_warehouse.component', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='templatecomponent',
            name='component',
            field=models.ForeignKey(blank=True, help_text='Součástka ze skladu (pokud byla nalezena)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_usages', to='nextintranet_warehouse.component', verbose_name='Component'),
        ),
    ]
