# Generated by Django 5.1.2 on 2026-02-16 00:00

import django.db.models.deletion
import nextintranet_production.models.production
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nextintranet_warehouse', '0051_alter_parametertype_value_type'),
        ('nextintranet_production', '0004_alter_realizationcomponent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='ibom_file',
            field=models.FileField(blank=True, null=True, upload_to=nextintranet_production.models.production.bom_ibom_upload_path, verbose_name='iBOM file'),
        ),
        migrations.AddField(
            model_name='template',
            name='ibom_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='iBOM updated at'),
        ),
        migrations.AddField(
            model_name='template',
            name='ibom_url',
            field=models.URLField(blank=True, null=True, verbose_name='iBOM URL'),
        ),
        migrations.AddField(
            model_name='template',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked at'),
        ),
        migrations.AddField(
            model_name='template',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_boms', to=settings.AUTH_USER_MODEL, verbose_name='Locked by'),
        ),
        migrations.AddField(
            model_name='template',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned date'),
        ),
        migrations.AddField(
            model_name='template',
            name='production_checkpoint',
            field=models.JSONField(blank=True, default=dict, help_text='Aggregated scanner checkpoint JSON used to restore UI state.', verbose_name='Production checkpoint'),
        ),
        migrations.AddField(
            model_name='template',
            name='qty_planned',
            field=models.PositiveIntegerField(default=1, help_text='How many boards are planned for this BOM.', verbose_name='Planned quantity'),
        ),
        migrations.AddField(
            model_name='template',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to=nextintranet_production.models.production.bom_source_upload_path, verbose_name='Source file'),
        ),
        migrations.AddField(
            model_name='template',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Source hash'),
        ),
        migrations.AddField(
            model_name='template',
            name='source_imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Source imported at'),
        ),
        migrations.AddField(
            model_name='template',
            name='source_url',
            field=models.URLField(blank=True, help_text='Optional URL used for BOM re-import.', null=True, verbose_name='Source URL'),
        ),
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('locked', 'Locked')], default='draft', help_text='Lifecycle status of this BOM.', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='bom_description',
            field=models.TextField(blank=True, null=True, verbose_name='BOM description'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='datasheet',
            field=models.TextField(blank=True, null=True, verbose_name='Datasheet'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='dnp',
            field=models.BooleanField(default=False, verbose_name='Do not populate'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='footprint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Footprint'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='import_snapshot',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Import snapshot'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='Needs review'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='placed_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Placed total'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='qty_override_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Qty override total'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='qty_per_board',
            field=models.PositiveIntegerField(default=1, verbose_name='Qty per board'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='ref_group',
            field=models.TextField(blank=True, help_text='Comma-separated designators from source netlist.', null=True, verbose_name='Ref group'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='refs',
            field=models.JSONField(blank=True, default=list, help_text='List of designators in this BOM row.', verbose_name='Refs'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='source_type',
            field=models.CharField(choices=[('imported', 'Imported'), ('manual', 'Manual')], default='imported', max_length=20, verbose_name='Source type'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='sourced_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Sourced total'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.CreateModel(
            name='TemplateComponentScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('sourced', 'Sourced'), ('placed', 'Placed')], max_length=20, verbose_name='Mode')),
                ('barcode', models.TextField(verbose_name='Barcode')),
                ('resolved_packet_id', models.UUIDField(blank=True, null=True, verbose_name='Resolved packet id')),
                ('qty', models.DecimalField(decimal_places=6, default=1, max_digits=20, verbose_name='Quantity')),
                ('resolved_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_scans', to='nextintranet_warehouse.component', verbose_name='Resolved component')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='nextintranet_production.template', verbose_name='Template')),
                ('template_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='nextintranet_production.templatecomponent', verbose_name='Template component')),
            ],
            options={
                'verbose_name': 'Template component scan',
                'verbose_name_plural': 'Template component scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
