# Generated by Django 6.0 on 2026-06-17 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0006_template_series_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateComponentRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(help_text='Designator, e.g. R1.', max_length=255, verbose_name='Reference')),
                ('tstamp', models.CharField(blank=True, help_text='KiCad instance UUID/tstamp, stable across netlist updates.', max_length=255, null=True, verbose_name='Netlist tstamp')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Per-reference netlist snapshot (fields, properties, raw).', verbose_name='Metadata')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_items', to='nextintranet_production.templatecomponent', verbose_name='BOM line')),
                ('template', models.ForeignKey(help_text='Denormalized for fast per-template ref lookups.', on_delete=django.db.models.deletion.CASCADE, related_name='ref_items', to='nextintranet_production.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Component Reference',
                'verbose_name_plural': 'Template Component References',
                'ordering': ['position', 'ref'],
                'indexes': [models.Index(fields=['template', 'ref'], name='nextintrane_templat_c8adcf_idx'), models.Index(fields=['line'], name='nextintrane_line_id_911998_idx')],
            },
        ),
    ]
