# Generated by Django 6.0 on 2026-07-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0008_populate_template_component_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecomponent',
            name='exclude_from_bom',
            field=models.BooleanField(default=False, help_text='Component is populated on the board but omitted from the BOM printout.', verbose_name='Exclude from BOM'),
        ),
    ]
