# Generated by Django 6.0 on 2026-07-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0009_template_component_exclude_from_bom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('locked', 'Locked'), ('finished', 'Finished')], default='draft', help_text='Lifecycle status of this BOM.', max_length=20, verbose_name='Status'),
        ),
    ]
