# Generated by Django 6.0 on 2026-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0010_alter_template_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='link',
            field=models.URLField(blank=True, help_text='HTTP odkaz související s výrobním projektem (např. dokumentace, specifikace)', max_length=2048, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='template',
            name='ibom_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='iBOM URL'),
        ),
        migrations.AlterField(
            model_name='template',
            name='source_url',
            field=models.URLField(blank=True, help_text='Optional URL used for BOM re-import.', max_length=2048, null=True, verbose_name='Source URL'),
        ),
    ]
