# Generated by Django 6.0 on 2026-08-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0011_alter_production_link_alter_template_ibom_url_and_more'),
        ('nextintranet_warehouse', '0065_packet_state_purchaseitem_draft_packet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecomponentscan',
            name='stock_operation',
            field=models.ForeignKey(blank=True, help_text='Warehouse deduction booked when this component was placed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_placed_scans', to='nextintranet_warehouse.stockoperation', verbose_name='Stock operation'),
        ),
    ]
