# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0012_templatecomponentscan_stock_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecomponent',
            name='side',
            field=models.CharField(
                choices=[('both', 'Both sides'), ('top', 'Top (front)'), ('bottom', 'Bottom (back)')],
                default='both',
                help_text='Which side of the board this component is populated on.',
                max_length=10,
                verbose_name='PCB side',
            ),
        ),
    ]
