# Generated by Django 6.0.6 on 2026-10-08 06:00

import django.db.models.deletion
from django.conf import settings
from collections import Counter

from django.db import migrations, models


def convert_production_reservations(apps, schema_editor):
    """Turn per-line production Reservation rows into a reserved BOM.

    The held quantity is now computed from the BOM, so the rows are deleted once their BOM is
    marked reserved. A BOM whose warehouse cannot be determined keeps its rows (they then act
    as manual reservations) and is reported."""
    Reservation = apps.get_model('nextintranet_warehouse', 'Reservation')
    Template = apps.get_model('nextintranet_production', 'Template')
    Warehouse = apps.get_model('nextintranet_warehouse', 'Warehouse')

    warehouse_ids = list(Warehouse.objects.filter(is_warehouse=True).values_list('id', flat=True)[:2])
    only_warehouse = warehouse_ids[0] if len(warehouse_ids) == 1 else None

    rows_by_bom = {}
    for reservation in Reservation.objects.all():
        for source in reservation.sources or []:
            if isinstance(source, dict) and source.get('type') == 'production' and source.get('bom_id'):
                rows_by_bom.setdefault(str(source['bom_id']), []).append(reservation)
                break

    for bom_id, rows in rows_by_bom.items():
        template = Template.objects.filter(id=bom_id).first()
        if template is None:
            continue
        warehouse_id = template.stock_warehouse_id or only_warehouse
        if warehouse_id is None:
            counts = Counter(r.warehouse_id for r in rows if r.warehouse_id is not None)
            warehouse_id = counts.most_common(1)[0][0] if counts else None
        if warehouse_id is None:
            print(f"\n  BOM {bom_id}: no warehouse could be determined, reservations kept as manual.")
            continue
        template.stock_warehouse_id = warehouse_id
        template.reserved_at = min(r.reservation_date for r in rows)
        template.save(update_fields=['stock_warehouse', 'reserved_at'])
        Reservation.objects.filter(id__in=[r.id for r in rows]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_production', '0013_templatecomponent_side'),
        ('nextintranet_warehouse', '0068_warehouse_flag_reservation_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='reserved_at',
            field=models.DateTimeField(blank=True, help_text='Set while the BOM holds stock. The held quantity is computed from the BOM lines.', null=True, verbose_name='Reserved at'),
        ),
        migrations.AddField(
            model_name='template',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_boms', to=settings.AUTH_USER_MODEL, verbose_name='Reserved by'),
        ),
        migrations.AddField(
            model_name='template',
            name='stock_warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse the BOM draws its parts from; its reservation holds stock there.', limit_choices_to={'is_warehouse': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_boms', to='nextintranet_warehouse.warehouse', verbose_name='Stock warehouse'),
        ),
        migrations.RunPython(convert_production_reservations, migrations.RunPython.noop),
    ]
