# Generated by Django 5.1.2 on 2025-01-20 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_backend', '0002_printlist_printitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='read', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'area'],
                'unique_together': {('user', 'area')},
            },
        ),
    ]
