# Generated by Codex on 2025-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_backend', '0003_useraccesspermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesspermission',
            name='level',
            field=models.CharField(
                choices=[
                    ('hidden', 'Hidden'),
                    ('guest', 'Guest'),
                    ('read', 'Read'),
                    ('write', 'Write'),
                    ('admin', 'Admin'),
                ],
                default='read',
                max_length=10
            ),
        ),
    ]
