# Generated by Django 6.0 on 2025-12-30 23:26

import nextintranet_backend.models.printList
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_backend', '0010_user_setting_home_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfile',
            name='file',
            field=models.FileField(upload_to=nextintranet_backend.models.printList.print_file_upload_path),
        ),
    ]
