# Generated by Django 6.0 on 2026-06-11 12:24

import nextintranet_backend.models.branding
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_backend', '0011_alter_printfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.FileField(blank=True, null=True, upload_to=nextintranet_backend.models.branding.branding_logo_upload_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branding settings',
                'verbose_name_plural': 'Branding settings',
            },
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('label_type', models.CharField(choices=[('packet', 'Packet'), ('location', 'Location'), ('component', 'Component')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('supported_formats', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('definition', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label_type', 'name'],
            },
        ),
    ]
