# Generated by Django 6.0 on 2026-07-24 07:48

import django.core.validators
import nextintranet_backend.models.branding
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_backend', '0013_seed_label_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(re.compile('^#[0-9A-Fa-f]{6}$'), 'Enter a valid hex color (e.g. #0f172a).')]),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='company_name',
            field=models.CharField(blank=True, default='NextIntranet', help_text='Full organization name used in the PWA manifest and page titles.', max_length=100),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='company_short_name',
            field=models.CharField(blank=True, default='NextIntranet', help_text='Short name displayed under the app icon on mobile home screens.', max_length=20),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='pwa_icon_192',
            field=models.FileField(blank=True, null=True, upload_to=nextintranet_backend.models.branding.branding_pwa_icon_192_upload_path),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='pwa_icon_512',
            field=models.FileField(blank=True, null=True, upload_to=nextintranet_backend.models.branding.branding_pwa_icon_512_upload_path),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='pwa_icon_maskable',
            field=models.FileField(blank=True, null=True, upload_to=nextintranet_backend.models.branding.branding_pwa_icon_maskable_upload_path),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='theme_color',
            field=models.CharField(blank=True, default='#0f172a', max_length=7, validators=[django.core.validators.RegexValidator(re.compile('^#[0-9A-Fa-f]{6}$'), 'Enter a valid hex color (e.g. #0f172a).')]),
        ),
    ]
