# Generated by Django 5.1.2 on 2024-12-25 23:13

import colorfield.fields
import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Contact information')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('link_template', models.CharField(blank=True, help_text="Template for generating the product link in the supplier's e-shop. Use {symbol} as a placeholder for the component symbol.", max_length=255, null=True, verbose_name='Link template')),
                ('min_order_quantity', models.PositiveIntegerField(default=1, help_text='Minimum order quantity for the supplier, e.g., items sold in packs of 10.', verbose_name='Minimum order quantity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('abbreviation', models.SlugField(unique=True, verbose_name='Abbreviation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='nextintranet_warehouse.category', verbose_name='Parent category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Markdown description', null=True)),
                ('unit_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float')], default='int', help_text='Defines whether the component is tracked in integer or float quantities (e.g., pieces vs meters).', max_length=10)),
                ('selling_price', models.FloatField(blank=True, help_text='Selling price per unit for external sales.', null=True)),
                ('internal_price', models.FloatField(blank=True, help_text='Price per unit for internal use.', null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='nextintranet_warehouse.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_trackable', models.BooleanField(default=False, help_text='Indicates if the component is trackable by individual pieces.', verbose_name='Is trackable')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='nextintranet_warehouse.component', verbose_name='Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('doc_type', models.CharField(choices=[('datasheet', 'Datasheet'), ('manual', 'Manual'), ('specification', 'Specification'), ('application_note', 'Application Note'), ('drawing', 'Drawing'), ('certificate', 'Certificate'), ('image', 'Image'), ('other', 'Other')], max_length=50, verbose_name='Document type')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='File')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_set', to='nextintranet_warehouse.component', verbose_name='Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='component',
            name='primary_image',
            field=models.ForeignKey(blank=True, help_text='Primary image for the component.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='nextintranet_warehouse.document'),
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='Identifier')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Parameter name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('categories', models.ManyToManyField(blank=True, related_name='parameter_types', to='nextintranet_warehouse.category', verbose_name='Applicable categories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='nextintranet_warehouse.component', verbose_name='Component')),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_parameters', to='nextintranet_warehouse.parametertype', verbose_name='Parameter type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_type', models.CharField(choices=[('selling', 'Selling'), ('internal', 'Internal')], max_length=10, verbose_name='Price type')),
                ('price', models.FloatField(verbose_name='Price')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='nextintranet_warehouse.component', verbose_name='Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('reserved_by', models.CharField(max_length=255, verbose_name='Reserved by')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='Reservation date')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration date')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='nextintranet_warehouse.component', verbose_name='Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('adjust', 'Adjust'), ('transfer', 'Transfer'), ('inventory', 'Inventory'), ('service', 'Service withdrawal'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=10, verbose_name='Operation type')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('relative_quantity', models.BooleanField(default=True, help_text='Indicates if the quantity is relative (e.g., added or removed) or an absolute value after the operation.', verbose_name='Relative quantity')),
                ('unit_price', models.FloatField(blank=True, help_text='Unit price for the operation, used for FIFO tracking.', null=True, verbose_name='Unit price')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='nextintranet_warehouse.batch', verbose_name='Batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=100, verbose_name='Supplier symbol')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_relations', to='nextintranet_warehouse.component', verbose_name='Component')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_relations', to='nextintranet_warehouse.supplier', verbose_name='Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='component',
            name='tags',
            field=models.ManyToManyField(blank=True, to='nextintranet_warehouse.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('can_store_items', models.BooleanField(default=False, help_text='Indicates if this location can store components.', verbose_name='Can store items')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='nextintranet_warehouse.warehouse', verbose_name='Parent unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='nextintranet_warehouse.warehouse', verbose_name='Warehouse'),
        ),
    ]
