# Generated by Django 5.1.2 on 2024-12-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0002_alter_category_options_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
