# Generated by Django 5.1.2 on 2024-12-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0004_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the document if hosted externally.', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('datasheet', 'Datasheet'), ('manual', 'Manual'), ('specification', 'Specification'), ('application_note', 'Application Note'), ('drawing', 'Drawing'), ('certificate', 'Certificate'), ('image', 'Image'), ('other', 'Other'), ('undefined', 'Undefined')], default='undefined', max_length=50, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
