# Generated by Django 5.1.2 on 2024-12-28 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0005_alter_category_options_document_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockoperation',
            name='batch',
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='nextintranet_warehouse.component', verbose_name='Component'),
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_trackable', models.BooleanField(default=False, help_text='Indicates if the component is trackable by individual pieces.', verbose_name='Is trackable')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='nextintranet_warehouse.component', verbose_name='Component')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='nextintranet_warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='packet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='nextintranet_warehouse.packet', verbose_name='Packet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
