# Generated by Django 5.1.2 on 2024-12-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0006_remove_stockoperation_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrelation',
            name='price_ranges',
            field=models.JSONField(blank=True, null=True, verbose_name='Price ranges'),
        ),
    ]
