# Generated by Django 5.1.2 on 2024-12-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0007_supplierrelation_price_ranges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierrelation',
            name='price_ranges',
        ),
        migrations.AddField(
            model_name='supplierrelation',
            name='api_data',
            field=models.JSONField(blank=True, null=True, verbose_name='api_data'),
        ),
    ]
