# Generated by Django 5.1.2 on 2024-12-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0008_remove_supplierrelation_price_ranges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrelation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
