# Generated by Django 5.1.2 on 2025-01-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0009_supplierrelation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrelation',
            name='custom_url',
            field=models.URLField(blank=True, null=True, verbose_name='Custom URL'),
        ),
    ]
