# Generated by Django 5.1.2 on 2025-01-04 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0010_supplierrelation_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='primary_image',
            field=models.ForeignKey(blank=True, help_text='Primary image for the component.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for', to='nextintranet_warehouse.document'),
        ),
        migrations.AlterField(
            model_name='componentparameter',
            name='parameter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_parameters', to='nextintranet_warehouse.parametertype', verbose_name='Parameter type'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='location',
            field=models.ForeignKey(help_text='Location of the batch in the warehouse.', limit_choices_to={'can_store_items': True}, on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='nextintranet_warehouse.warehouse', verbose_name='Packet location'),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='nextintranet_warehouse.packet', verbose_name='Packet'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='nextintranet_warehouse.component', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='custom_url',
            field=models.URLField(blank=True, help_text="Custom URL for the component in the supplier's e-shop. Use this field to override the link template in suppliers profile.", null=True, verbose_name='Custom URL'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='description',
            field=models.TextField(blank=True, help_text="Description of the component in the supplier's e-shop.", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier of the item.', on_delete=django.db.models.deletion.CASCADE, related_name='component_relations', to='nextintranet_warehouse.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='symbol',
            field=models.CharField(help_text="Supplier's symbol (order code) for the item.", max_length=100, verbose_name='Supplier symbol'),
        ),
    ]
