# Generated by Django 5.1.2 on 2025-01-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0011_alter_component_primary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentparameter',
            name='parameter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_parameters', to='nextintranet_warehouse.parametertype', verbose_name='Parameter type'),
        ),
    ]
