# Generated by Django 5.1.2 on 2025-01-05 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0012_alter_componentparameter_parameter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametertype',
            name='categories',
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='previous_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_operation', to='nextintranet_warehouse.stockoperation', verbose_name='Previous operation. Null for the first operation in the batch.'),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='operation_type',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('adjust', 'Adjust'), ('trans_in', 'Transfer in'), ('trans_out', 'Transfer out'), ('inventory', 'Inventory'), ('service', 'Service withdrawal'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=10, verbose_name='Operation type'),
        ),
    ]
