# Generated by Django 5.1.2 on 2025-01-05 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0013_remove_parametertype_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='last_operation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_operation', to='nextintranet_warehouse.stockoperation', verbose_name='Last operation'),
        ),
    ]
