# Generated by Django 5.1.2 on 2025-01-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0014_packet_last_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='nextintranet_warehouse.component', verbose_name='Component'),
        ),
    ]
