# Generated by Django 5.1.2 on 2025-01-13 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0015_alter_document_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery date')),
                ('stocked_date', models.DateField(blank=True, null=True, verbose_name='Stocked date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status')),
                ('currency', models.CharField(max_length=10, verbose_name='Currency')),
                ('total_price_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total price (original currency) without VAT')),
                ('total_price_original_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total price (original currency) with VAT')),
                ('total_price_converted', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total price (converted to our currency)')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nextintranet_warehouse.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, verbose_name='Symbol')),
                ('unit_price_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit price (original currency)')),
                ('unit_price_converted', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit price (converted currency)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('package_size', models.PositiveIntegerField(verbose_name='Package size')),
                ('is_fully_delivered', models.BooleanField(default=False, verbose_name='Fully delivered')),
                ('delivered_quantity', models.PositiveIntegerField(default=0, verbose_name='Delivered quantity')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='nextintranet_warehouse.component', verbose_name='Component')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nextintranet_warehouse.purchase', verbose_name='Purchase')),
                ('supplier_relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='nextintranet_warehouse.supplierrelation', verbose_name='Supplier item')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Delivery date')),
                ('delivered_quantity', models.PositiveIntegerField(verbose_name='Delivered quantity')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='nextintranet_warehouse.purchaseitem', verbose_name='Purchase Item')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
