# Generated by Django 5.1.2 on 2025-02-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0016_purchase_purchaseitem_purchasedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price_converted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total price (converted to our currency)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total price (original currency) without VAT'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price_original_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total price (original currency) with VAT'),
        ),
    ]
