# Generated by Django 5.1.2 on 2025-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0017_alter_purchase_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='abbreviation',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
