# Generated by Django 5.1.2 on 2025-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0018_remove_category_abbreviation_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametertype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='parametertype',
            name='name',
        ),
        migrations.AlterField(
            model_name='parametertype',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Parameter name'),
        ),
    ]
