# Generated by Django 5.1.2 on 2025-03-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0019_remove_parametertype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertype',
            name='special_meaning',
            field=models.BooleanField(default=False, verbose_name='Special meaning'),
        ),
    ]
