# Generated by Django 5.1.2 on 2025-03-03 13:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0020_parametertype_special_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbreviation',
            field=models.SlugField(default='', unique=True, verbose_name='Abbreviation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametertype',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Parameter name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parametertype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
