# Generated by Django 5.1.2 on 2025-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0021_category_abbreviation_parametertype_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='primary_image',
            field=models.CharField(blank=True, help_text='URL of the primary image for the component.', max_length=255, null=True),
        ),
    ]
