# Generated by Django 5.1.2 on 2025-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0022_alter_component_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoperation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
