# Generated by Django 5.1.2 on 2025-03-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0024_stockoperation_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
    ]
