# Generated by Django 5.1.2 on 2025-03-06 00:14

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0025_alter_supplier_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktaking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_from', models.DateTimeField(blank=True, null=True)),
                ('open_until', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='stocktaking_authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stocktaking',
                'verbose_name_plural': 'Stocktakings',
            },
        ),
    ]
