# Generated by Django 5.1.2 on 2025-03-24 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0026_stocktaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoperation',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='componentparameter',
            name='parameter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nextintranet_warehouse.parametertype', verbose_name='Parameter type'),
        ),
        migrations.AlterField(
            model_name='componentparameter',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value'),
        ),
    ]
