# Generated by Django 5.1.2 on 2025-03-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0027_stockoperation_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierrelation',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier of the item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_relations', to='nextintranet_warehouse.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='symbol',
            field=models.CharField(blank=True, help_text="Supplier's symbol (order code) for the item.", max_length=100, null=True, verbose_name='Supplier symbol'),
        ),
    ]
