# Generated by Django 5.1.2 on 2025-03-28 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0028_alter_supplierrelation_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location of the batch in the warehouse.', limit_choices_to={'can_store_items': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='nextintranet_warehouse.warehouse', verbose_name='Packet location'),
        ),
    ]
