# Generated by Django 5.1.2 on 2025-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0029_alter_packet_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockoperation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Stock operation', 'verbose_name_plural': 'Stock operations'},
        ),
        migrations.AddField(
            model_name='packet',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='packet',
            name='itemValue',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Item Value'),
        ),
        migrations.AddField(
            model_name='packet',
            name='totalValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Value'),
        ),
    ]
