# Generated by Django 5.1.2 on 2025-03-29 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0030_alter_stockoperation_options_packet_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockoperation',
            name='reference',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Reference to the stocktaking or other operation.', null=True, verbose_name='Reference'),
        ),
    ]
