# Generated by Django 5.1.2 on 2025-12-26 00:40

import django.db.models.deletion
from django.db import migrations, models


def remove_null_purchase_items(apps, schema_editor):
    PurchaseItem = apps.get_model('nextintranet_warehouse', 'PurchaseItem')
    PurchaseItem.objects.filter(component__isnull=True).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('nextintranet_warehouse', '0037_purchase_invoice_and_manual_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='name',
        ),
        migrations.RunPython(remove_null_purchase_items, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='purchaseitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='nextintranet_warehouse.component', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='supplier_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='nextintranet_warehouse.supplierrelation', verbose_name='Supplier item'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='symbol',
            field=models.CharField(max_length=100, verbose_name='Symbol'),
        ),
    ]
