# Generated by Django 5.1.2 on 2025-12-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0038_migrate_component_primary_image'),
        ('nextintranet_warehouse', '0038_remove_document_access_level_and_more'),
    ]

    operations = [
    ]
