# Generated by Django 6.0 on 2025-12-26 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0039_merge_20251226_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='nextintranet_warehouse.component', verbose_name='Component'),
        ),
    ]
