# Generated by Django 6.0 on 2025-12-30 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_backend', '0011_alter_printfile_file'),
        ('nextintranet_warehouse', '0045_supplier_api_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='api_last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='API last sync at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='api_mapping',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='API mapping'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='api_plugin_instance',
            field=models.OneToOneField(blank=True, help_text='Plugin instance used for supplier component API calls.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_api', to='nextintranet_backend.plugininstance', verbose_name='API plugin instance'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='api_applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='API applied at'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='api_data_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='API data hash'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='api_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='API fetched at'),
        ),
    ]
