# Generated by Django 6.0 on 2025-12-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0046_alter_supplier_api_last_sync_at_and_more'),
        ('nextintranet_warehouse', '0046_supplier_api_config'),
    ]

    operations = [
    ]
