# Generated by Django 6.0 on 2025-12-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0047_merge_20251230_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='api_config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='API config'),
        ),
    ]
