# Generated by Django 6.0 on 2026-02-15

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


MAX_DECIMAL_DIGITS = 100
MAX_DECIMAL_PLACES = 40


def _parse_decimal_for_storage(raw_value):
    if raw_value is None:
        return None
    value_text = str(raw_value).strip()
    if not value_text:
        return None
    try:
        parsed = Decimal(value_text)
    except InvalidOperation:
        return None

    normalized = parsed.normalize()
    _, digits, exponent = normalized.as_tuple()
    significant_digits = len(digits)
    if exponent >= 0:
        whole_digits = significant_digits + exponent
        decimal_places = 0
    else:
        whole_digits = max(significant_digits + exponent, 0)
        decimal_places = -exponent

    if decimal_places > MAX_DECIMAL_PLACES:
        return None
    if whole_digits > (MAX_DECIMAL_DIGITS - MAX_DECIMAL_PLACES):
        return None
    if significant_digits > MAX_DECIMAL_DIGITS:
        return None
    return parsed


def backfill_value_number(apps, schema_editor):
    ComponentParameter = apps.get_model("nextintranet_warehouse", "ComponentParameter")

    queryset = ComponentParameter.objects.select_related("parameter_type").all()
    for component_parameter in queryset.iterator(chunk_size=500):
        normalized_value = None
        parameter_type = component_parameter.parameter_type
        if parameter_type and parameter_type.value_type == "number":
            normalized_value = _parse_decimal_for_storage(component_parameter.value)
        ComponentParameter.objects.filter(pk=component_parameter.pk).update(
            value_number=normalized_value
        )


class Migration(migrations.Migration):

    dependencies = [
        ("nextintranet_warehouse", "0048_alter_supplier_api_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametertype",
            name="format_with_si_prefix",
            field=models.BooleanField(default=False, verbose_name="Format with SI prefix"),
        ),
        migrations.AddField(
            model_name="componentparameter",
            name="value_number",
            field=models.DecimalField(
                blank=True,
                decimal_places=40,
                max_digits=100,
                null=True,
                verbose_name="Numeric value",
            ),
        ),
        migrations.AddIndex(
            model_name="componentparameter",
            index=models.Index(
                fields=["parameter_type", "value_number"],
                name="ni_wh_param_type_num_idx",
            ),
        ),
        migrations.RunPython(backfill_value_number, migrations.RunPython.noop),
    ]
