# Generated by Django 6.0 on 2026-02-15 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0049_parameter_numeric_si_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentparameter',
            name='is_inherited',
            field=models.BooleanField(default=False, verbose_name='Is inherited'),
        ),
        migrations.CreateModel(
            name='CategoryParameterRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value_template', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_rules', to='nextintranet_warehouse.category')),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextintranet_warehouse.parametertype')),
            ],
            options={
                'unique_together': {('category', 'parameter_type')},
            },
        ),
        migrations.AddField(
            model_name='componentparameter',
            name='source_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nextintranet_warehouse.categoryparameterrule', verbose_name='Source rule'),
        ),
    ]
