# Generated by Django 6.0 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextintranet_warehouse", "0050_parameter_inheritance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametertype",
            name="value_type",
            field=models.CharField(
                choices=[("text", "Text"), ("number", "Number"), ("bool", "Boolean")],
                default="text",
                max_length=10,
                verbose_name="Value type",
            ),
        ),
    ]
