# Generated by Django 6.0 on 2026-02-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nextintranet_warehouse', '0053_purchase_delivery_stocking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identifier',
            options={'verbose_name': 'External identifier', 'verbose_name_plural': 'External identifiers'},
        ),
        migrations.AddField(
            model_name='identifier',
            name='scheme',
            field=models.CharField(blank=True, choices=[('', 'Internal'), ('ean', 'EAN'), ('sku', 'SKU'), ('supplier', 'Supplier code'), ('other', 'Other')], default='', help_text='Type of identifier (EAN, SKU, etc.). Empty = internal.', max_length=50, verbose_name='Scheme'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='identifier',
            field=models.CharField(max_length=255, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='identifier',
            constraint=models.UniqueConstraint(fields=('scheme', 'identifier'), name='identifier_unique_scheme_value'),
        ),
    ]
