# Generated by Django 6.0 on 2026-05-22 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nextintranet_warehouse', '0057_reservation_sources'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resourceaccesslog',
            new_name='nextintrane_content_7049ca_idx',
            old_name='nextintrane_content_8c0b0d_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('datasheet', 'Datasheet'), ('manual', 'Manual'), ('specification', 'Specification'), ('application_note', 'Application Note'), ('drawing', 'Drawing'), ('certificate', 'Certificate'), ('image', 'Image'), ('product_page', 'Product page'), ('other', 'Other'), ('undefined', 'Undefined')], default='undefined', max_length=50, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='resourceaccesslog',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'nextintranet_warehouse'), ('model', 'component')), models.Q(('app_label', 'nextintranet_warehouse'), ('model', 'packet')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='supplierrelation',
            name='api_availability',
            field=models.CharField(blank=True, help_text='Availability or stock info from supplier API (e.g. "In Stock", lead time).', max_length=255, null=True, verbose_name='API availability'),
        ),
    ]
