# Generated by Django 6.0 on 2026-06-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0058_rename_nextintrane_content_8c0b0d_idx_nextintrane_content_7049ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoperation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='scheme',
            field=models.CharField(blank=True, choices=[('', 'Internal'), ('ean', 'EAN'), ('sku', 'SKU'), ('supplier', 'Supplier code'), ('legacy', 'Legacy barcode'), ('other', 'Other')], default='', help_text='Type of identifier (EAN, SKU, etc.). Empty = internal.', max_length=50, verbose_name='Scheme'),
        ),
    ]
