# Generated by Django 6.0 on 2026-07-29 14:12

import django.db.models.deletion
from django.db import migrations, models


def backfill_packet_state(apps, schema_editor):
    Packet = apps.get_model('nextintranet_warehouse', 'Packet')
    Packet.objects.filter(is_active=False).update(state='retired')
    Packet.objects.filter(is_active=True).update(state='stocked')


def reverse_backfill(apps, schema_editor):
    Packet = apps.get_model('nextintranet_warehouse', 'Packet')
    Packet.objects.filter(state__in=['stocked', 'in_transit']).update(is_active=True)
    Packet.objects.exclude(state__in=['stocked', 'in_transit']).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0064_packet_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='state',
            field=models.CharField(choices=[('expected', 'Expected'), ('stocked', 'Stocked'), ('in_transit', 'In transit'), ('retired', 'Retired')], db_index=True, default='stocked', help_text='Physical lifecycle of the packet. Drives is_active.', max_length=16, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='draft_packet',
            field=models.ForeignKey(blank=True, help_text='Packet created when the order was exported, in the expected state until stocked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='nextintranet_warehouse.packet', verbose_name='Draft packet'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Derived from state; kept for backwards compatibility.', verbose_name='Is active'),
        ),
        migrations.RunPython(backfill_packet_state, reverse_backfill),
    ]
