# Generated by Django 6.0.6 on 2026-08-23 23:13

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0065_packet_state_purchaseitem_draft_packet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nextintranet_warehouse.purchaserequestfolder', verbose_name='Parent folder')),
            ],
            options={
                'verbose_name': 'Purchase request folder',
                'verbose_name_plural': 'Purchase request folders',
            },
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='nextintranet_warehouse.purchaserequestfolder', verbose_name='Folder'),
        ),
    ]
