# Generated by Django 6.0.6 on 2026-08-24 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0066_purchaserequestfolder_purchaserequest_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockoperation',
            index=models.Index(fields=['-timestamp'], name='stockop_time_idx'),
        ),
    ]
