# Generated by Django 6.0.6 on 2026-10-07 13:28

import django.db.models.deletion
from collections import defaultdict

from django.db import migrations, models


def flag_roots_and_scope_reservations(apps, schema_editor):
    """Root locations become warehouses; existing reservations get the warehouse they most
    plausibly hold stock in (the only warehouse, else the one holding most of the component)."""
    Warehouse = apps.get_model('nextintranet_warehouse', 'Warehouse')
    Packet = apps.get_model('nextintranet_warehouse', 'Packet')
    Reservation = apps.get_model('nextintranet_warehouse', 'Reservation')

    Warehouse.objects.filter(parent__isnull=True).update(is_warehouse=True)
    root_by_tree = dict(Warehouse.objects.filter(parent__isnull=True).values_list('tree_id', 'id'))
    if not root_by_tree:
        return
    only_root = next(iter(root_by_tree.values())) if len(root_by_tree) == 1 else None

    for reservation in Reservation.objects.filter(warehouse__isnull=True):
        warehouse_id = only_root
        if warehouse_id is None:
            stock = defaultdict(float)
            packets = Packet.objects.filter(
                component_id=reservation.component_id, state='stocked', location__isnull=False
            ).values_list('location__tree_id', 'count')
            for tree_id, count in packets:
                stock[root_by_tree.get(tree_id)] += float(count or 0)
            stock.pop(None, None)
            if stock:
                warehouse_id = max(stock, key=stock.get)
        if warehouse_id is not None:
            reservation.warehouse_id = warehouse_id
            reservation.save(update_fields=['warehouse'])


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0067_stockoperation_stockop_time_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse the stock is held in. Empty only for legacy rows; those hold stock in every warehouse.', limit_choices_to={'is_warehouse': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='nextintranet_warehouse.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_warehouse',
            field=models.BooleanField(default=False, help_text='Marks this location as a warehouse. Stock and reservations are scoped to the nearest warehouse above a location.', verbose_name='Is warehouse'),
        ),
        migrations.RunPython(flag_roots_and_scope_reservations, migrations.RunPython.noop),
    ]
