# Generated by Django 6.0.6 on 2026-10-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0068_warehouse_flag_reservation_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='source',
            field=models.JSONField(blank=True, default=dict, help_text='Where the request came from, e.g. {"type": "production", "bom_id": "...", "line_id": "..."}.', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='target_location',
            field=models.ForeignKey(blank=True, help_text='Warehouse or position the requested parts should end up in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='nextintranet_warehouse.warehouse', verbose_name='Target location'),
        ),
    ]
