# Generated by Django 6.0.6 on 2026-10-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0069_purchaserequest_target_location_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseactivity',
            name='activity_type',
            field=models.CharField(choices=[('scan', 'Scan'), ('stock_operation', 'Stock operation'), ('packet_created', 'Packet created'), ('packet_updated', 'Packet updated'), ('packet_moved', 'Packet moved'), ('packet_status_changed', 'Packet status changed'), ('component_created', 'Component created'), ('component_updated', 'Component updated'), ('identifier_added', 'Identifier added'), ('identifier_removed', 'Identifier removed'), ('reservation_created', 'Reservation created'), ('reservation_updated', 'Reservation updated'), ('reservation_deleted', 'Reservation deleted'), ('bom_reserved', 'BOM reserved'), ('bom_unreserved', 'BOM unreserved')], max_length=50, verbose_name='Activity type'),
        ),
    ]
