# Generated by Django 6.0.6 on 2026-10-08 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextintranet_warehouse', '0070_warehouseactivity_reservation_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('source', models.JSONField(blank=True, default=dict, help_text='Where the request came from, e.g. {"type": "production", "bom_id": "...", "line_id": "..."}.', verbose_name='Source')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='nextintranet_warehouse.component', verbose_name='Component')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
                ('source_warehouse', models.ForeignKey(limit_choices_to={'is_warehouse': True}, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='nextintranet_warehouse.warehouse', verbose_name='From warehouse')),
                ('target_location', models.ForeignKey(help_text='Warehouse or storage position the parts should be moved to.', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='nextintranet_warehouse.warehouse', verbose_name='To location')),
            ],
            options={
                'verbose_name': 'Transfer request',
                'verbose_name_plural': 'Transfer requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
